# Site
name: "Dunia Selebriti"
description: 'Berita Seputar Selebriti '
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
url: "https://iinewstech.com"
baseurl: '/'
disqus: 'dunia-selebriti'
email: 'emmamery93@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    merry:
      name:           Merry
      site:           https://iinewstech.com/
      avatar:         /assets/images/avatar1.png
      bio:            "Hi sama ............................................."
      email:          emmamery93@gmail.com 
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: merry
      avatar: /assets/images/avatar1.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
